[project]
name = "new-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ai-edge-torch==0.4.0",
    "jax[cuda12]>=0.5.3",
    "matplotlib>=3.10.3",
    "numpy>=2.1.3",
    "onnx2tf>=1.27.7",
    "opencv-python>=4.11.0.86",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
    "pydantic>=2.11.4",
    "rich>=14.0.0",
    "scikit-learn>=1.6.1",
    "tf-keras>=2.19.0",
    "torch>=2.6.0",
    "torchmetrics>=1.7.1",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "typer[all]>=0.15.4",
]
