[project]
name = "new-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "torch",
    "tensorflow==2.12",
    "onnx-tf",
    "typer",
    "pydantic",
    "tensorflow-probability==0.20.0",
    "tensorflow-addons==0.20.0",
    "tf_keras",
    "torchvision>=0.22.0",
]
[tool.uv.sources]
onnx-tf = { path = "./onnx-tensorflow" }
