[project]
name = "new-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.7.9"
dependencies = [
    "torch==1.5.1",
    "onnx==1.7.0",
    "tensorflow==2.2.0",
    "tensorflow-addons==0.11.2",
    "onnx-tf==1.6.0"
]
